[package]
name = "rca-infra"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
async-trait.workspace = true
chrono = { workspace = true, features = ["serde"] }
directories = "6.0.0"
futures-core.workspace = true
futures-util = "0.3"
keyring = "3.6.3"
notify-rust = "4.12.0"
rca-core = { version = "0.1.0", path = "../rca-core" }
reqwest = { version = "0.13.2", features = ["json", "rustls"] }
semver = "1.0.27"
pdf-writer = "0.13"
image = { version = "0.25", default-features = false, features = [
    "jpeg",
    "png",
] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
    "fs",
] }
tokio-tungstenite = { version = "0.28.0", features = [
    "rustls-tls-webpki-roots",
] }
tracing.workspace = true
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url.workspace = true
rust-i18n.workspace = true

[dev-dependencies]
mockall = "0.14"
tempfile = "3"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
mockito = "1.7"
