[package]
name = "rca-infra"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []

[dependencies]
async-trait.workspace = true
chrono = { workspace = true, features = ["serde"] }
directories.workspace = true
futures-core.workspace = true
futures-util.workspace = true
keyring.workspace = true
notify-rust = "4.12.0"
rca-core = { version = "0.1.0", path = "../rca-core" }
reqwest = { workspace = true, features = ["json", "rustls"] }
semver = "1.0.27"
pdf-writer = "0.14"
image = { workspace = true, default-features = false, features = [
    "jpeg",
    "png",
] }
bytes = "1"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
    "fs",
] }
tokio-tungstenite = { version = "0.29.0", features = [
    "rustls-tls-webpki-roots",
] }
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url.workspace = true
rust-i18n.workspace = true

[dev-dependencies]
mockall = "0.14"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
mockito = "1.7"
tempfile = "3"
lopdf = "0.40"
