[package]
name = "rca-desktop"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
rca-app = { version = "0.1.0", path = "../../crates/rca-app" }
rca-core = { version = "0.1.0", path = "../../crates/rca-core" }
slint.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
chrono.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing-appender = "0.2.4"
rust-i18n.workspace = true

[build-dependencies]
slint-build.workspace = true
