[package]
name = "rca-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []

[dependencies]
rca-app = { version = "0.1.0", path = "../../crates/rca-app" }
rca-core = { version = "0.1.0", path = "../../crates/rca-core" }
rca-infra = { version = "0.1.0", path = "../../crates/rca-infra" }
clap.workspace = true
qrcode = "0.14"
image = { workspace = true, default-features = false, features = ["png", "jpeg", "gif", "webp"] }
reqwest = { workspace = true }
rqrr = "0.10"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "signal"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender.workspace = true
rust-i18n.workspace = true
indicatif = "0.18.4"
